---
# Please see roles/container-engine/containerd/defaults/main.yml for more configuration options

# containerd_storage_dir: "/var/lib/containerd"
# containerd_state_dir: "/run/containerd"
# containerd_oom_score: 0

# containerd_default_runtime: "runc"
# containerd_snapshotter: "native"

# containerd_runc_runtime:
#   name: runc
#   type: "io.containerd.runc.v2"
#   engine: ""
#   root: ""

# containerd_additional_runtimes:
# Example for Kata Containers as additional runtime:
#   - name: kata
#     type: "io.containerd.kata.v2"
#     engine: ""
#     root: ""

# containerd_grpc_max_recv_message_size: 16777216
# containerd_grpc_max_send_message_size: 16777216

# Containerd debug socket location: unix or tcp format
# containerd_debug_address: ""

# Containerd log level
# containerd_debug_level: "info"

# Containerd logs format, supported values: text, json
# containerd_debug_format: ""

# Containerd debug socket UID
# containerd_debug_uid: 0

# Containerd debug socket GID
# containerd_debug_gid: 0

# containerd_metrics_address: ""

# containerd_metrics_grpc_histogram: false

# Registries defined within containerd.
# containerd_registries_mirrors:
#  - prefix: docker.io
#    mirrors:
#     - host: https://registry-1.docker.io
#       capabilities: ["pull", "resolve"]
#       skip_verify: false

# Using the new, recommended containerd_registries_mirrors variable.
containerd_registries_mirrors:
  # For docker.io
  - prefix: docker.io
    mirrors:
      - host: "http://jyow:5000"
        capabilities: ["pull", "resolve", "push"]

  # For registry.k8s.io
  - prefix: registry.k8s.io
    mirrors:
      - host: "http://jyow:5000"
        capabilities: ["pull", "resolve", "push"]

  # For gcr.io
  - prefix: gcr.io
    mirrors:
      - host: "http://jyow:5000"
        capabilities: ["pull", "resolve", "push"]

  # For quay.io
  - prefix: quay.io
    mirrors:
      - host: "http://jyow:5000"
        capabilities: ["pull", "resolve", "push"]

  # ====================================================================
  # [추가된 부분] 로컬 레지스트리의 IP 주소를 직접 지정
  # This ensures pulls work even if the hostname 'jyow' cannot be resolved.
  # ====================================================================
  - prefix: 10.0.1.6:5000
    mirrors:
      - host: "http://10.0.1.6:5000"
        capabilities: ["pull", "resolve", "push"]


# containerd_max_container_log_line_size: 16384

# containerd_registry_auth:
#   - registry: 10.0.0.2:5000
#     username: user
#     password: pass
